### ISSUE TITLE
Add script name in the `nps is executing` output

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/nps#126]
Right now if I execute:

```
nps f.b
```

I'll get something like:

```
nps executing: echo "foo bar"
```

I'd like it to say:

```
nps is executing foo.bar: echo "foo bar"
```

where `foo.bar` is the name (path) of the script being executed. It'd be good to get it in bold too.

Anyone wanna take this up?

**Comment by Miklet** [comment]
Since my PR for `prefix-matches` got merged and now it returns corresponding property chain I can get back to this issue. I have question about module `resolve-script-object-to-string` if it is still needed after changes. Result of `prefix-matches` will now always return an object and also we want now to get resolved prefix with script to execute, not only script.

**Comment by kentcdodds** [comment]
Yes, the PR to support this will be much simpler now :)

**Comment by Miklet** [comment]
If it will be much simpler then I guess we can drop module `resolve-script-object-to-string` as I asked earlier :)?

**Comment by kentcdodds** [comment]
I expect so :) Thanks so much!
